#! /usr/bin/perl
use lib qw( ./lib ../lib );
use Algorithm::Numerical::Shuffle qw( shuffle );
use FreeScore::Test qw( score_worldclass );
use Time::HiRes qw( usleep );

our $test  = new FreeScore::Test();

my $number = $test->worldclass( "judges" );
my $judges = $number->{ judges } - 1;
my $skill  = [ qw( good better best better best better ok good ok good ok better ok good best good better ok good better good good ) ];

foreach my $athlete ( 0 .. 21 ) {
	foreach my $form ( 0 .. 1 ) {
		score( $skill->[ $athlete ], $judges );
		$test->worldclass( "form/next" );
	}
	$test->worldclass( "athlete/next" );

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 21;
}

sleep( 3 );
$test->worldclass( "round/next" );

foreach my $athlete ( 0 .. 10 ) {
	foreach my $form ( 0 .. 1 ) {
		score( 'better', $judges );
		$test->worldclass( "form/next" );
	}
	$test->worldclass( "athlete/next" );

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 10;
}

sleep( 3 );
$test->worldclass( "round/next" );

foreach my $athlete ( 0 .. 7 ) {
	foreach my $form ( 0 .. 1 ) {
		score( 'best', $judges );
		$test->worldclass( "form/next" );
	}
	$test->worldclass( "athlete/next" );

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 7;
}

# ============================================================
sub score {
# ============================================================
	my $skill  = shift;
	my $k      = shift;
	my @judges = shuffle( 0 .. $k );
	foreach my $judge (@judges) {
		my $score       = score_worldclass( $skill );
		my $judge_score = join( "/", $judge, (map { $_ * 10 } @{ $score }{ qw( major minor rhythm power ki ) }));
		$test->worldclass( $judge_score );
		usleep( 125000 );
	}
	usleep( 500000 );
}
