#! /usr/bin/perl
use lib qw( ./lib ../lib );
use Algorithm::Numerical::Shuffle qw( shuffle );
use FreeScore::Test qw( score_worldclass );
use Time::HiRes qw( usleep );

our $test  = new FreeScore::Test();

my $number = $test->worldclass( "judges" );
my $judges = $number->{ judges } - 1;
my $names  = [ 'Aditya', 'Anika', 'Piper', 'Alexander', 'Steven', 'Sofia', 'Christian', 'Jamsheed', 'Thibault', 'Yash', 'Sean C.', 'Sean O.', 'Sujatha', 'Jill', 'Mike', 'Carl', 'Veronika', 'Giovanni', 'Katrina', 'Cody', 'Kaylee', 'Jonathan' ];
my $skill  = {
	'Aditya'	=> 'good',
	'Anika'		=> 'better',
	'Piper'		=> 'best',
	'Alexander'	=> 'better',
	'Steven'	=> 'best',
	'Sofia'		=> 'better',
	'Christian'	=> 'ok',
	'Jamsheed'	=> 'good',
	'Thibault'	=> 'ok',
	'Yash'		=> 'good',
	'Sean C.'	=> 'ok',
	'Sean O.'	=> 'better',
	'Sujatha'	=> 'ok',
	'Jill'		=> 'good',
	'Mike'		=> 'best',
	'Carl'		=> 'good',
	'Veronika'	=> 'better',
	'Giovanni'	=> 'ok',
	'Katrina'	=> 'good',
	'Cody'		=> 'better',
	'Kaylee'	=> 'good',
	'Jonathan'	=> 'good'
};
my $current = 0;

foreach my $athlete ( 0 .. 21 ) {
	foreach my $form ( 0 .. 1 ) {
		my $name  = $names->[ $current ];
		my $level = $skill->{ $name };
		score( $level, $judges );
		$test->worldclass( "form/next" );
	}
	$current = $test->worldclass( "athlete/next" );
	$current = $current->{ athlete };

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 21;
}

sleep( 3 );
$current = $test->worldclass( "round/next" );
$current = $current->{ athlete };

foreach my $athlete ( 0 .. 10 ) {
	foreach my $form ( 0 .. 1 ) {
		my $name  = $names->[ $current ];
		my $level = $skill->{ $name };
		score( $level, $judges );
		$test->worldclass( "form/next" );
	}
	$current = $test->worldclass( "athlete/next" );
	$current = $current->{ athlete };

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 10;
}

sleep( 3 );
$current = $test->worldclass( "round/next" );
$current = $current->{ athlete };

foreach my $athlete ( 0 .. 7 ) {
	foreach my $form ( 0 .. 1 ) {
		my $name  = $names->[ $current ];
		my $level = $skill->{ $name };
		score( $level, $judges );
		$test->worldclass( "form/next" );
	}
	$current = $test->worldclass( "athlete/next" );
	$current = $current->{ athlete };

	$test->worldclass( "display" );
	sleep( 1 );
	$test->worldclass( "display" ) unless $athlete == 7;
}

# ============================================================
sub score {
# ============================================================
	my $skill  = shift;
	my $k      = shift;
	my @judges = shuffle( 0 .. $k );
	foreach my $judge (@judges) {
		my $score       = score_worldclass( $skill );
		my $judge_score = join( "/", $judge, (map { $_ * 10 } @{ $score }{ qw( major minor rhythm power ki ) }));
		$test->worldclass( $judge_score );
		usleep( 125000 );
	}
	usleep( 500000 );
}
