.PHONY: all setup worldclass grassroots freestyle

all: setup grassroots worldclass freestyle

worldclass:
	sudo hypnotoad -f ./bin/worldclass &

grassroots:
	sudo hypnotoad -f ./bin/grassroots &

freestyle:
	sudo hypnotoad -f ./bin/freestyle &

setup:
	sudo hypnotoad -f ./bin/fswifi &
