#! /usr/bin/perl
use Try::Tiny;
use CGI;
use CGI::Carp qw( fatalsToBrowser );
use List::Util qw( first );
use File::Slurp qw( read_file );
use JSON::XS;
use Data::Dumper;

use lib qw( /usr/local/freescore/lib );
use FreeScore::Forms::FreeStyle;

my $cgi        = new CGI();
my $results    = undef;
my $tournament = read_tournament_config();
my $ring       = $cgi->param( 'ring' );
my $divid      = $cgi->param( 'divid' );
my @rounds     = ($cgi->param( 'round' ));
my $json       = new JSON::XS;

my @divisions  = ();
my $results    = undef;
try {
	if( defined $ring ) {
		if( defined $divid ) {
			$results = new FreeScore::Forms::FreeStyle( $tournament->{ db }, $ring );
			push @divisions, grep { $_->{ name } eq $divid } @{ $results->{ divisions }};

		} else {
			$results = new FreeScore::Forms::FreeStyle( $tournament->{ db }, $ring );
			push @divisions, @{ $results->{ divisions }};
		}
	} else {
		foreach my $ring ( @{$tournament->{ rings }} ) {
			$results = new FreeScore::Forms::FreeStyle( $tournament->{ db }, $ring );
			push @divisions, @{ $results->{ divisions }};
		}
	}
} catch {
	die $_;

};

@divisions = sort { $a->{ name } cmp $b->{ name } } @divisions;

print $cgi->header();

my $branding_css = "/var/www/html/images/branding/branding.css";
$branding_css = -e $branding_css ? read_file( $branding_css ) : '';

print <<EOF;
<html>
	<head>
		<title>Freestyle Poomsae TA Sheets</title>
		<style type="text/css">
				body { font-family: Optima; }
				.division {
					clear: both;
					margin-top: 28px;
					width: 920px;
					height: 20px;
				}
				.division .description { float: left; }
				.division .round { float: right; }
				.results {
					page-break-inside: avoid;
					page-break-after: always;
				}
				.results table { width: 920px; }
				.results th {
					margin-top: 8px;
					border-top: 1px solid #999;
					border-bottom: 1px solid #999;
					padding: 0 4px 0 4px;
					text-align: left;
				}
				.results .number    { width: 32px; }
				.results .usat      { width: 80px; }
				.results .noc		{ width: 63px; }
				.results .athlete   { width: 768px; }
				.results .form      { width: 100px; text-align: center; }
				.results td.decisions { width: 32px; text-align: center; color: red; }
				.results td         { padding: 2px 4px 2px 4px; }
				.results td.score   { text-align: center; }
				.results td.preacc  { font-size: 8pt; }
				.results tr:nth-child( even ) { background: #fff; }
				.results tr:nth-child( odd  ) { background: #eee; }
				.results tr:nth-child( even ) td { border-bottom: 1px solid #fff; }
				.results tr:nth-child( odd  ) td { border-bottom: 1px solid #eee; }

				$branding_css
    		</style>
  		</head>
  	<body>
<table>
<thead><tr><td><div class="header-space"> </div></td></tr></thead>
<tbody><tr><td>
EOF
foreach my $division (@divisions) {
	my $name   = uc $division->{ name };
	my $judges = $division->{ judges } || 3;
	@rounds = ( qw( finals semfin prelim )) unless @rounds;
	foreach my $round (@rounds) {
		next unless exists $division->{ order }{ $round };
		my $rname  = { prelim => 'Preliminary Round', semfin => 'Semi-Finals Round', finals => 'Finals Round' }->{ $round };
		my $placed = {};
		my $i      = 0;
		my $places = $division->{ placements }{ $round };
		foreach my $j ( 0 .. $#$places ) {
			my $i = $places->[ $j ];
			$placed->{ $i } = ordinal( $j + 1 );
		}

		print <<EOF;
		<div class="results">
		<div class="division"><div class="description"><b>Division $name</b> &mdash; $division->{ description } </div><div class="round"><b>$rname</b></div></div>
		<table border=0 cellpadding=0 cellspacing=0>
			<tr>
				<th class="number">#</th>
				<th class="noc">NOC</th>
				<th class="athlete">Name</th>
				<th class="form">Freestyle</th>
				<th class="decisions">Decisions</th>
			</tr>
EOF
		my $n = $#{$division->{ order }{ $round }};
		foreach my $i (0 .. $n) {
			my $j       = $division->{ order }{ $round }[ $i ];
			my $athlete = $division->{ athletes }[ $j ];
			my $noc     = $athlete->{ info }{ noc };
			$noc = $noc =~ /\// ? (split /\//, $noc)[ -1 ] : $noc;
			my $notes   = $athlete->{ notes } ? $athlete->{ notes } : '';
      my $video = $json->encode( $athlete->{ info }{ video }{ $round } );
			my $stream = $json->encode( $athlete->{ info }{ stream } );
			my $decision = "";
			if ($video =~ /(WDR|DSQ)/) {
				$decision = $&;
			} elsif ($stream =~ /(WDR|DSQ)/) {
				$decision = $&;
			}
			my $sum     = 0.0;
			my $n       = 0;
			print "<tr><td class=\"number\">" . ($i + 1) . ".</td><td class=\"noc\">$noc</td><td class=\"athlete\">$athlete->{ name }</td><td class=\"form\"></td>";
			my $score  = $athlete->{ adjusted }{ $round };
				print "<td class=\"decisions\">$decision</td>";
			print "</tr>\n";
		}
		print <<EOF;
		</table>
		</div>
EOF
	}
}

print <<EOF;
</td></tr></tbody>
<tfoot><tr><td><div class="footer-space"> </div></td></tr></tfoot>
</table>
<div class="header"><img src="/images/branding/header.png" width="100%"></div>
<div class="footer"><img src="/images/branding/footer.png" width="100%"></div>
  </body>
</html>
EOF

# ============================================================
sub ordinal {
# ============================================================
	my $n = shift;
	my $d = $n % 10;
	if( $n >= 11 && $n <= 13 ) { return $n . 'th'; }
	elsif( $d == 1 )           { return $n . 'st'; }
	elsif( $d == 2 )           { return $n . 'nd'; }
	elsif( $d == 3 )           { return $n . 'rd'; }
	else                       { return $n . 'th'; }
}

# ============================================================
sub read_tournament_config {
# ============================================================
	my $php = '';
	my $config = {
		optscore => '/home/ubuntu/freescore/trunk/frontend/html/include/php/config.php',
		redhat   => '/var/www/html/freescore/include/php/config.php',
		ubuntu   => '/var/www/freescore/include/php/config.php',
		raspbian => '/var/www/html/include/php/config.php',
	};
	foreach $os (keys %$config) { if( -e $config->{ $os } ) { $php = $config->{ $os }; last; } }
	if( ! $php ) { die "Can't find configuration file 'config.php' $!"; }

	my $json = new JSON::XS();
	my $data = `(cat $php; echo '<?php echo \$tournament ?>') | php`;
	my $config = $json->decode( $data );
	return $config;
}
