#! /usr/bin/perl
use Try::Tiny;
use JSON::XS;
use File::Slurp qw( read_file );
use Data::Structure::Util qw( unbless );
use List::Util qw( first );
use List::MoreUtils qw( first_index );
use Clone qw( clone );
use Data::Dumper;
use Cwd qw( getcwd );

use lib qw( /usr/local/freescore/lib );
use FreeScore::Forms::WorldClass;
use FreeScore::Forms::FreeStyle;

$FreeScore::PATH = getcwd();

my $json       = new JSON::XS();

my $divisions  = [];

foreach my $day (map { sprintf( "day-%d-complete", $_ )} ( 1 .. 6 )) {
	next unless -e "$FreeScore::PATH/$day";
	foreach my $ring ( 1 .. 4 ) {
		my $rname = sprintf( "ring%02d", $ring );
		next unless -e "$FreeScore::PATH/$day/$FreeScore::Forms::WorldClass::SUBDIR/$rname";
		my $results = new FreeScore::Forms::WorldClass( $day, $ring );
		push @$divisions, @{ $results->{ divisions }};
	}
	@$divisions = sort { $a->{ name } cmp $b->{ name } } grep { $_->{ name } !~ /^gr0[45][01]$/ } @$divisions;
	print_divisions( $divisions );
}

# ============================================================
sub print_divisions {
# ============================================================
	my $divisions = shift;
	foreach my $division (@$divisions) {
		my $divid      = $division->{ name };
		my $divdesc    = sprintf( "%-64s", substr( $division->{ description }, 0, 64 ));
		my $athletes   = $division->{ athletes };
		foreach my $round ( qw( prelim semfin finals )) {
			next unless( exists( $division->{ order }{ $round }) && exists( $division->{ placement }{ $round }));
			foreach my $i (@{$division->{ order }{ $round }}) {
				my $athlete  = $division->{ athletes }[ $i ];
				my $place    = first_index { $i == $_ } @{ $division->{ placement }{ $round }};
				my $name     = $athlete->{ name };
				my $noc      = $athlete->{ info }{ noc };
				my $video    = $json->decode( $athlete->{ info }{ video });
				my $uuid     = (split /\//, $video->{ $round }[ 0 ]{ file })[ 0 ];
				my $decision = $video->{ $round }[ 0 ]{ decision };
				if( $place < 0 ) { $place = '-'; } else { $place = $place + 1; }
				$place = $decision if $decision;

				print "$divid\t$divdesc\t$round\t$place\t$uuid\t$noc\t$name\n";
			}
		}
	}
}
