#! /usr/bin/perl

use lib qw( /Users/mikewong899/devel/freescore/backend/lib );
use Mojolicious::Lite;
use YAML;
use FreeScore::Forms::GrassRoots::Division;
use FreeScore::Forms::GrassRoots;

srand();

# ============================================================
# JUDGE INTERFACE
# ============================================================

# ------------------------------------------------------------
# NEXT DIVISION
# ------------------------------------------------------------
get '/:tournament/next' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $progress = new FreeScore::Forms::GrassRoots( $tournament );
	$progress->next();
	$progress->write();
	$self->render( json => { 'current' => $progress->current() } );
};

# ------------------------------------------------------------
# PREVIOUS DIVISION
# ------------------------------------------------------------
get '/:tournament/previous' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $progress = new FreeScore::Forms::GrassRoots( $tournament );
	$progress->previous();
	$progress->write();
	$self->render( json => { 'current' => $progress->current() } );
};
# ------------------------------------------------------------
# CHANGE CURRENT DIVISION STATE TO SCORE
# ------------------------------------------------------------
get '/:tournament/:division/score' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $forms = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$forms->score();
	$forms->write();
	$self->render( json => { 'state' => $forms->{ state } } );
};

# ------------------------------------------------------------
# CHANGE CURRENT DIVISION STATE TO DISPLAY
# ------------------------------------------------------------
get '/:tournament/:division/display' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $forms = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$forms->display();
	$forms->write();
	$self->render( json => { 'state' => $forms->{ state } } );
};

# ------------------------------------------------------------
# SCORE FOR NEXT ATHLETE
# ------------------------------------------------------------
get '/:tournament/:division/next' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $forms = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$forms->next();
	$forms->write();
	$self->render( json => { 'current' => $forms->{ current }, 'state' => $forms->{ state } } );
};

# ------------------------------------------------------------
# SCORE FOR PREVIOUS ATHLETE
# ------------------------------------------------------------
get '/:tournament/:division/previous' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $forms = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$forms->previous();
	$forms->write();
	$self->render( json => { 'current' => $forms->{ current }, 'state' => $forms->{ state } } );
};

# ------------------------------------------------------------
# WRITE JUDGE SCORE FOR ATHLETE
# ------------------------------------------------------------
get '/:tournament/:division/:athlete/:judge/:score' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $athlete    = $self->param( 'athlete' );
	my $judge      = $self->param( 'judge' );
	my $score      = $self->param( 'score' ) / 10;
	my $forms      = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$forms->{ division }[ $athlete ]{ scores }[ $judge ] = $score;
	$forms->write();
	$self->render( json => { athlete => $athlete, judge => ($judge + 1), score => $score } );
};

# ============================================================
# GRASSROOTS FORMS
# ============================================================

# ------------------------------------------------------------
# DIVISION LIST
# ------------------------------------------------------------
get '/:tournament' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = new FreeScore::Forms::GrassRoots( $tournament );
	my $forms      = new FreeScore::Forms::GrassRoots::Division( $tournament, $division->current() );
	
	$self->render( json => { id => $division->current(), current => $forms->{ current }, state => $forms->{ state }, athletes => $forms->{ division } } );
};

# ------------------------------------------------------------
# DIVISION STATUS
# ------------------------------------------------------------
get '/:tournament/:division' => sub { 
	my $self       = shift;
	my $tournament = $self->param( 'tournament' );
	my $division   = $self->param( 'division' );
	my $forms = new FreeScore::Forms::GrassRoots::Division( $tournament, $division );
	$self->render( json => { current => $forms->{ current }, state => $forms->{ state }, athletes => $forms->{ division } } );
};


any '*' => sub {
	my $self = shift;
	$self->render( text => 'Unknown command' );
};


app->start( 'cgi' );
